export const authConstants = {

    GETALLCATEGORY_SUCCESS: "GETALLCATEGORY_SUCCESS",
    GETALLCATEGORY_FILURE: "GETALLCATEGORY_FILURE",


    PRODUCT_SUCCESS: "PRODUCT_SUCCESS",
    PRODUCT_FILURE: "PRODUCT_FILURE",


    GETPRODUCTBYSLUG_SUCCESS: "GETPRODUCTBYSLUG_SUCCESS",
    GETPRODUCTBYSLUG_FILURE: "GETPRODUCTBYSLUG_FILURE",


    GETNEWPAGEBYCATEGORY_SUCCESS: "GETNEWPAGEBYCATEGORY_SUCCESS",
    GETNEWPAGEBYCATEGORY_FILURE: "GETNEWPAGEBYCATEGORY_FILURE",



    GETHIGHLIGHT_SUCCESS: "GETHIGHLIGHT_SUCCESS",
    GETHIGHLIGHT_FILURE: "GETHIGHLIGHT_FILURE",


    GETPRODUCTBYFILTERSLUG_SUCCESS: "GETPRODUCTBYFILTERSLUG_SUCCESS",
    GETPRODUCTBYFILTERSLUG_FILURE: "GETPRODUCTBYFILTERSLUG_FILURE",

    GETPRODUCTDETAIL_SUCCESS: "GETPRODUCTDETAIL_SUCCESS",
    GETPRODUCTDETAIL_FILURE: "GETPRODUCTDETAIL_FILURE",

    SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
    SIGNIN_FILURE: "SIGNIN_FILURE",

    SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
    SIGNOUT_FILURE: "SIGNOUT_FILURE",


    ADDTOCART_SUCCESS: "ADDTOCART_SUCCESS",
    ADDTOCART_FILURE: "ADDTOCART_FILURE",

    GETCARTITEM_SUCCESS:"GETCARTITEM_SUCCESS",
    GETCARTITEM_FILURE:"GETCARTITEM_FILURE",


    RESET_CART:"RESET_CART",

GETADDRESS_SUCCESS:"GETADDRESS_SUCCESS",

ADDORDER_SUCCESS:"ADDORDER_SUCCESS",

ADDORDER_FAILURE:"ADDORDER_FAILURE",

ADDADDRESS_SUCCESS:"ADDADDRESS_SUCCESS"


}

